name: nanopore-metagenomics
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core dependencies
  - python=3.9
  - pip>=21.0
  - numpy>=1.21
  - pandas>=1.3
  - matplotlib>=3.4
  - seaborn>=0.11
  - biopython>=1.79
  - pyyaml>=5.4
  - jinja2>=3.0
  
  # Preprocessing tools
  - porechop=0.2.4
  - nanofilt=2.8.0
  - nanostat=1.6.0
  
  # Assembly tools
  - flye=2.9.2
  - minimap2=2.24
  - samtools=1.16.1
  - racon=1.5.0
  
  # Taxonomic classification
  - kraken2=2.1.2
  - bracken=2.8
  - diamond=2.1.8
  
  # Annotation tools
  - prokka=1.14.6
  - prodigal=2.6.3
  - hmmer=3.3.2
  - infernal=1.1.4
  - aragorn=1.2.38
  - barrnap=0.9
  - minced=0.4.2
  - tbl2asn-forever=25.7.2f
  - parallel=20230322
  
  # AMR detection
  - abricate=1.0.1
  - ncbi-amrfinderplus=3.11.11
  
  # Binning and quality assessment
  - metawrap=1.3.2
  - checkm-genome=1.2.2
  - maxbin2=2.2.7
  - metabat2=2.15
  - concoct=1.1.0
  
  # Additional analysis tools
  - fastqc=0.11.9
  - multiqc=1.14
  - bbmap=39.01
  - seqkit=2.3.1
  - csvtoolkit=1.0.1
  
  # Visualization and reporting
  - plotly>=5.0
  - bokeh>=2.4
  - altair>=4.2
  
  # Development tools
  - jupyter>=1.0
  - ipython>=7.30
  - black>=22.0
  - flake8>=4.0
  - pytest>=7.0
  
  # System utilities
  - pigz
  - pbzip2
  - git
  - wget
  - curl
  
  # R dependencies for some tools
  - r-base>=4.1
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  
  # Pip-only packages
  - pip:
    - eggnog-mapper==2.1.12
    - bakta==1.8.2
    - plasmidfinder==2.1.6
    - kofamscan==1.3.0
    - gtdbtk==2.3.0
    - metagenome-atlas==2.15.0
    - metaphlan==4.0.6
    - humann==3.6
    - anvi'o==7.1
    - drep==3.4.0
    - das_tool==1.1.5
    - coverm==0.6.1
    - instrain==1.6.1
    - genomad==1.5.0
    - vcontact2==0.11.3
    - vibrant==1.2.1
    - checkv==1.0.1
    - mob-suite==3.1.4
    - pycoQC==2.5.2
    - NanoPlot==1.41.0
    - medaka==1.8.0
    - filtlong==0.2.1

# Post-installation notes:
# 1. Some tools may require additional database downloads
# 2. Dorado must be installed separately from Oxford Nanopore
# 3. Some tools may require manual compilation or special installation procedures
# 4. Database paths must be configured in config/config.yaml
